var BATTLECRUISER = {
    name: 'battlecruiser',
    path: './img/defenders/battlecruiser/',
    sprites: ['portrait.jpg', 'idle.png', 'projectile.png'],
    cost: 300,
    range: 5,
    cooldown: 3,
    damage: 275,
    armorPiercing: true,
    hotkey: 'b',
    targetGround: true,
    targetFlying: false,
    frameWidth: 111,
    frameHeight: 81,
    sheetWidth: 32,
    frameDuration: 0.1,
    frames: 32,
    loop: true,
    scale: .5
};

var FIREBAT = {
    name: 'firebat',
    path: './img/defenders/firebat/',
    sprites: ['portrait.png', 'idle.png', 'shoot.png', 'projectile.png'],
    cost: 300,
    range: 2,
    cooldown: 0,
    damage: 50,
    armorPiercing: false,
    hotkey: 'f',
    targetGround: true,
    targetFlying: false,
    frameWidth: 31,
    frameHeight: 31,
    sheetWidth: 16,
    frameDuration: 0.1,
    frames: 16,
    loop: true,
    scale: 1.2
};

var GHOST = {
    name: "ghost",
    path: './img/defenders/ghost/',
    sprites: ['portrait.png', 'idle.png', 'shoot.png'],
    cost: 300,
    range: 100,
    cooldown: 0.5,
    damage: 35,
    armorPiercing: true,
    hotkey: 'g',
    targetGround: true,
    targetFlying: false,
    frameWidth: 40,
    frameHeight: 36,
    sheetWidth: 29,
    frameDuration: 0.1,
    frames: 29,
    loop: true,
    scale: 1.2
};

var MARINE = {
    name: 'marine',
    path: './img/defenders/marine/',
    sprites: ['portrait.jpg', 'idle.png', 'shoot.png'],
    cost: 300,
    range: 100,
    cooldown: 0.2,
    damage: 13,
    armorPiercing: false,
    hotkey: 'm',
    targetGround: true,
    targetFlying: true,
    frameWidth: 64,
    frameHeight: 64,
    sheetWidth: 32,
    frameDuration: 0.1,
    frames: 32,
    loop: true,
    scale: 1.2
};

var SCV = {
    name: 'scv',
    path: './img/defenders/scv/',
    sprites: ['portrait.png'],
    cost: 300,
    range: 0,
    cooldown: 1,
    damage: 0,
    armorPiercing: false,
    hotkey: 's',
    targetGround: false,
    targetFlying: false,
    frameWidth: 40,
    frameHeight: 41,
    sheetWidth: 1,
    frameDuration: 0.1,
    frames: 1,
    loop: true,
    scale: 1,
    speed: 65,
    direction: "west",
    gatherTime: 2.8
}

var TURRET = {
    name: 'turret',
    path: './img/defenders/turret/',
    sprites: ['portrait.png', 'idle.png', 'projectile.png'],
    cost: 300,
    range: 150,
    cooldown: 0.55,
    damage: 60,
    armorPiercing: true,
    mapKey: 't',
    targetGround: false,
    targetFlying: true,
    frameWidth: 43,
    frameHeight: 55,
    sheetWidth: 16,
    frameDuration: 0.1,
    frames: 16,
    loop: true,
    scale: 1
};

var DEFENDER_PROPERTIES = [BATTLECRUISER, FIREBAT, GHOST, MARINE, SCV, TURRET];